server:
  port: 8080
  address: 192.168.50.1


management.endpoints.web:
    base-path: /
    exposure.include: "*"


spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origins:
              - "*"
            allowed-methods:
              - "*"
            allowed-headers:
              - "*"
      routes:
        - id: school-api
          uri: lb://school-api
          predicates:
            - Path=/api/school/**
          filters:
            - RewritePath=/api/school/(?<request>.*), /$\{request}
        - id: student-api
          uri: lb://student-api
          predicates:
            - Path=/api/student/**
          filters:
            - RewritePath=/api/student/(?<request>.*), /$\{request}
